import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import MuiRTLConfig from "./mui-RTL";

// ---------------------------

const IRANSansX = localFont({
  src: "../public/fonts/IRANSansX-Light.woff2",
  variable: "--font-iransansx",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Dashboard-Ts",
  description: "Generated by Amir mohammad",
};

// ---------------------------

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={` ${IRANSansX.className} `}>
        <MuiRTLConfig>{children}</MuiRTLConfig>
      </body>
    </html>
  );
}
