import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import MuiRTLConfig from "./mui-RTL";
import { Toaster } from "react-hot-toast";
import Providers from "./services/react-query-config";
import { AntdRegistry } from '@ant-design/nextjs-registry';

// ---------------------------

const IRANSansX = localFont({
  src: "../public/fonts/IRANSansX-Light.woff2",
  variable: "--font-iransansx",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Dashboard-Next.js",
  description: "Generated by Amir mohammad",
};

// ---------------------------

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={` ${IRANSansX.className} `}>
        <Providers>
          <MuiRTLConfig>
            <AntdRegistry>
              {children}
            </AntdRegistry>
          </MuiRTLConfig>
        </Providers>
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
